print("Lists in Python are used to store multiple items in a single variable.")
my_list = [1, 2, 3, 4, 5]
print("The list is:", my_list)
print("The first item of the list is:", my_list[0])
print("The last item of the list is:", my_list[-1])
print("Slicing in Python is used to access a range of items in a list.")
print("The first 3 items of the list are:", my_list[:3])
print("The last 3 items of the list are:", my_list[-3:])
print("Tuples in Python are used to store multiple items in a single variable.")

my_tuple = (1, 2, 3, 4, 5)
print("The tuple is:", my_tuple)
print("The first item of the tuple is:", my_tuple[0])
print("The last item of the tuple is:", my_tuple[-1])
print("Slicing in Python is used to access a range of items in a tuple.")
print("The first 3 items of the tuple are:", my_tuple[:3])
print("The last 3 items of the tuple are:", my_tuple[-3:])

print("Differences between lists and tuples in Python:")
print("1. Lists are mutable, tuples are immutable.")
print("2. Lists are defined with square brackets [], tuples are defined with parentheses ().")
print("3. Lists have more built-in methods than tuples.")
print("4. Lists are slower than tuples due to their mutability.")
print("5. Lists holds variables of same data type, tuples can hold variables of different data types.")

print("The list after appending an item is:", my_list)
my_list.append(6)
print("The list after inserting an item at index 2 is:", my_list)
my_list.insert(2, 10)
print("The list after removing an item is:", my_list)
my_list.remove(3)
print("The list after popping an item is:", my_list)
my_list.pop()
print("The list after sorting is:", my_list)
my_list.sort()
print("Sorted list:", my_list)

